global using DotNetStarter.Core.Builder;
global using DotNetStarter.Core.Constants;
global using DotNetStarter.Core.Entities;
global using DotNetStarter.Core.Factories;
global using DotNetStarter.Core.Interfaces;
global using DotNetStarter.Core.Utils;
global using Spectre.Console;
global using System.Diagnostics;
global using System.Xml.Linq;
