name: .NET Build, Check, Pack and Publish

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código
    - name: Checkout repository
      uses: actions/checkout@v3

    # Configura o .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0

    # Extrai ou gera a versão (com base no Git)
    - name: Extract or generate version
      id: version
      run: |
        # Se a tag existir, use-a como versão; caso contrário, incremente manualmente.
        if git describe --tags --abbrev=0; then
          VERSION=$(git describe --tags --abbrev=0 | sed 's/^v//')
        else
          VERSION="1.0.0" # Padrão caso nenhuma tag exista
        fi

        # Adicione +1 na versão patch (exemplo: 1.0.0 -> 1.0.1)
        PATCH=$(echo $VERSION | awk -F. '{print $3+1}')
        VERSION=$(echo $VERSION | awk -F. '{print $1"."$2}')".$PATCH"

        echo "Version: $VERSION"
        echo "##[set-output name=VERSION;$VERSION]"

    # Atualiza a versão no arquivo .csproj
    - name: Update version in .csproj
      run: |
        sed -i 's|<Version>.*</Version>|<Version>${{ steps.version.outputs.VERSION }}</Version>|g' DotNetStarter/DotNetStarter.CLI.csproj

    # Restaura as dependências do projeto
    - name: Restore dependencies
      run: dotnet restore

    # Compila o projeto
    - name: Build solution
      run: dotnet build --configuration Release

    # Verifica a formatação do código
    - name: Format code
      run: dotnet format ./DotNetStarter.sln --check

    # Empacota o projeto para NuGet
    - name: Pack NuGet Package
      run: dotnet pack DotNetStarter.sln --configuration Release -o ./nupkg -p:PackageVersion=${{ steps.version.outputs.VERSION }}

    # Publica no NuGet
    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./nupkg/DotNetStarter.CLI.${{ steps.version.outputs.VERSION }}.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
